- name: Setting Password Authentication
  copy:
    src: /etc/ansible/roles/ssh/files/sshd_config_ubuntu
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644

- name: Restart SSH service
  service:
    name: ssh
    state: restarted
