---

- include: centos.yml
  when:
    - ansible_os_family == "RedHat"

- include: ubuntu.yml
  when:
    - ansible_os_family == "Debian"

- name: Setting Up Hostname
  action: command hostname {{hostname}}
